name: build-and-push


on: [push, workflow_dispatch]


permissions:
  contents: read
  packages: write
  actions: write


jobs:
  init-environments:
    name: Init Environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find commit short sha
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      sha_short: ${{ steps.short_sha.outputs.sha_short }}


  build-and-push:
    runs-on: ubuntu-latest

    needs: init-environments

    steps:
      - uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_IO_REGISTRY_USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: final
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ needs.init-environments.outputs.sha_short }}