name: tests


on: [push, workflow_dispatch]


permissions:
  contents: read
  packages: write
  actions: write


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Playwright Test
        uses: docker/build-push-action@v6
        with:
          push: false
          target: test